// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1dhp2JYG_q8R71hDAbFoKIoVe8sJNr0',
    appId: '1:492117491640:web:4e5c92d5980015bec3594d',
    messagingSenderId: '492117491640',
    projectId: 'skills-arena-c2c71',
    authDomain: 'skills-arena-c2c71.firebaseapp.com',
    storageBucket: 'skills-arena-c2c71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNox_MHUiLbtJKldUC5Wtezw3UfAuOJOM',
    appId: '1:492117491640:android:3a0e63d78f085e34c3594d',
    messagingSenderId: '492117491640',
    projectId: 'skills-arena-c2c71',
    storageBucket: 'skills-arena-c2c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAudLx1gb34WwyVj61BQidt-As7ATYMQ',
    appId: '1:492117491640:ios:f524e28eed161514c3594d',
    messagingSenderId: '492117491640',
    projectId: 'skills-arena-c2c71',
    storageBucket: 'skills-arena-c2c71.firebasestorage.app',
    iosClientId: '492117491640-512olk2ok7srtru2g5ceh8pq5sgugigm.apps.googleusercontent.com',
    iosBundleId: 'com.r27systems.skillsArena',
  );

}